-- Run in Supabase SQL editor (or psql) once before first judge-ingest.
-- Table for Soul → Supabase ingest used by Annotator Judge flow (separate from new_evaluation_table).
-- Judge outputs are stored in dedicated columns (no JSONB blob).

CREATE TABLE IF NOT EXISTS annotator_judge_table (
  id BIGSERIAL PRIMARY KEY,
  created_at TIMESTAMPTZ,
  user_id TEXT,
  email TEXT,
  status TEXT,
  task_allocation_id TEXT,
  updated_at TIMESTAMPTZ,
  subtask_id TEXT,
  punt_a TEXT,
  instruction_a TEXT,
  context_awareness_a TEXT,
  relevance_a TEXT,
  completeness_a TEXT,
  writing_style_a TEXT,
  collab_a TEXT,
  factuality_a TEXT,
  info_retrieval_a TEXT,
  code_a TEXT,
  code_sequence_a TEXT,
  code_output_a TEXT,
  overall_a TEXT,
  punt_b TEXT,
  instruction_b TEXT,
  context_awareness_b TEXT,
  relevance_b TEXT,
  completeness_b TEXT,
  writing_style_b TEXT,
  collab_b TEXT,
  factuality_b TEXT,
  info_retrieval_b TEXT,
  code_b TEXT,
  code_sequence_b TEXT,
  code_output_b TEXT,
  overall_b TEXT,
  likert_scale TEXT,
  justification TEXT,
  ingest_status TEXT DEFAULT 'PENDING',
  aj_eval_completed_at TIMESTAMPTZ,
  aj_eval_status TEXT,
  aj_m1_punt_a_match BOOLEAN,
  aj_m1_punt_a_penalty DOUBLE PRECISION,
  aj_m1_punt_b_match BOOLEAN,
  aj_m1_punt_b_penalty DOUBLE PRECISION,
  aj_m1_instruction_a_match BOOLEAN,
  aj_m1_instruction_a_penalty DOUBLE PRECISION,
  aj_m1_instruction_b_match BOOLEAN,
  aj_m1_instruction_b_penalty DOUBLE PRECISION,
  aj_m1_context_awareness_a_match BOOLEAN,
  aj_m1_context_awareness_a_penalty DOUBLE PRECISION,
  aj_m1_context_awareness_b_match BOOLEAN,
  aj_m1_context_awareness_b_penalty DOUBLE PRECISION,
  aj_m1_relevance_a_match BOOLEAN,
  aj_m1_relevance_a_penalty DOUBLE PRECISION,
  aj_m1_relevance_b_match BOOLEAN,
  aj_m1_relevance_b_penalty DOUBLE PRECISION,
  aj_m1_completeness_a_match BOOLEAN,
  aj_m1_completeness_a_penalty DOUBLE PRECISION,
  aj_m1_completeness_b_match BOOLEAN,
  aj_m1_completeness_b_penalty DOUBLE PRECISION,
  aj_m1_writing_style_a_match BOOLEAN,
  aj_m1_writing_style_a_penalty DOUBLE PRECISION,
  aj_m1_writing_style_b_match BOOLEAN,
  aj_m1_writing_style_b_penalty DOUBLE PRECISION,
  aj_m1_collab_a_match BOOLEAN,
  aj_m1_collab_a_penalty DOUBLE PRECISION,
  aj_m1_collab_b_match BOOLEAN,
  aj_m1_collab_b_penalty DOUBLE PRECISION,
  aj_m1_factuality_a_match BOOLEAN,
  aj_m1_factuality_a_penalty DOUBLE PRECISION,
  aj_m1_factuality_b_match BOOLEAN,
  aj_m1_factuality_b_penalty DOUBLE PRECISION,
  aj_m1_info_retrieval_a_match BOOLEAN,
  aj_m1_info_retrieval_a_penalty DOUBLE PRECISION,
  aj_m1_info_retrieval_b_match BOOLEAN,
  aj_m1_info_retrieval_b_penalty DOUBLE PRECISION,
  aj_m1_code_a_match BOOLEAN,
  aj_m1_code_a_penalty DOUBLE PRECISION,
  aj_m1_code_b_match BOOLEAN,
  aj_m1_code_b_penalty DOUBLE PRECISION,
  aj_m1_code_sequence_a_match BOOLEAN,
  aj_m1_code_sequence_a_penalty DOUBLE PRECISION,
  aj_m1_code_sequence_b_match BOOLEAN,
  aj_m1_code_sequence_b_penalty DOUBLE PRECISION,
  aj_m1_code_output_a_match BOOLEAN,
  aj_m1_code_output_a_penalty DOUBLE PRECISION,
  aj_m1_code_output_b_match BOOLEAN,
  aj_m1_code_output_b_penalty DOUBLE PRECISION,
  aj_m1_overall_a_match BOOLEAN,
  aj_m1_overall_a_penalty DOUBLE PRECISION,
  aj_m1_overall_b_match BOOLEAN,
  aj_m1_overall_b_penalty DOUBLE PRECISION,
  aj_m1_dimension_score DOUBLE PRECISION,
  aj_final_score DOUBLE PRECISION,
  aj_m2_coherence_score DOUBLE PRECISION,
  aj_m2_claim_verification TEXT,
  aj_m2_rating_alignment TEXT,
  aj_m2_likert_consistency TEXT,
  aj_m2_logical_flow TEXT,
  aj_m2_issues_text TEXT,
  aj_m2_explanation TEXT,
  aj_m3_compliance_score DOUBLE PRECISION,
  aj_m3_overall_compliance TEXT,
  aj_m3_defensible_disagreements TEXT,
  aj_m3_clear_errors TEXT,
  aj_m3_summary_explanation TEXT,
  aj_m3_dimension_assessments_text TEXT,
  aj_flagged BOOLEAN,
  aj_flag_reasons TEXT,
  aj_eval_annotator_likert TEXT,
  aj_golden_likert TEXT,
  aj_likert_match BOOLEAN,
  aj_likert_penalty DOUBLE PRECISION
);

CREATE INDEX IF NOT EXISTS idx_annotator_judge_subtask_id ON annotator_judge_table (subtask_id);
CREATE INDEX IF NOT EXISTS idx_annotator_judge_created_at ON annotator_judge_table (created_at);
CREATE INDEX IF NOT EXISTS idx_annotator_judge_email ON annotator_judge_table (email);
