-- Gold labels for annotator-judge accuracy (AE-v1). Run once in Supabase SQL editor.
-- Join key: subtask_id (aligns with annotator_judge_table.subtask_id from Soul previous_data ->> 'uniqueId').

CREATE TABLE IF NOT EXISTS "golden-mock-tasking" (
  subtask_id TEXT PRIMARY KEY,
  punt_a TEXT,
  punt_a_priority TEXT,
  instruction_a TEXT,
  instruction_a_priority TEXT,
  context_awareness_a TEXT,
  context_awareness_a_priority TEXT,
  relevance_a TEXT,
  relevance_a_priority TEXT,
  completeness_a TEXT,
  completeness_a_priority TEXT,
  writing_style_a TEXT,
  writing_style_a_priority TEXT,
  collab_a TEXT,
  collab_a_priority TEXT,
  factuality_a TEXT,
  factuality_a_priority TEXT,
  info_retrieval_a TEXT,
  info_retrieval_a_priority TEXT,
  code_a TEXT,
  code_a_priority TEXT,
  code_sequence_a TEXT,
  code_sequence_a_priority TEXT,
  code_output_a TEXT,
  code_output_a_priority TEXT,
  overall_a TEXT,
  overall_a_priority TEXT,
  punt_b TEXT,
  punt_b_priority TEXT,
  instruction_b TEXT,
  instruction_b_priority TEXT,
  context_awareness_b TEXT,
  context_awareness_b_priority TEXT,
  relevance_b TEXT,
  relevance_b_priority TEXT,
  completeness_b TEXT,
  completeness_b_priority TEXT,
  writing_style_b TEXT,
  writing_style_b_priority TEXT,
  collab_b TEXT,
  collab_b_priority TEXT,
  factuality_b TEXT,
  factuality_b_priority TEXT,
  info_retrieval_b TEXT,
  info_retrieval_b_priority TEXT,
  code_b TEXT,
  code_b_priority TEXT,
  code_sequence_b TEXT,
  code_sequence_b_priority TEXT,
  code_output_b TEXT,
  code_output_b_priority TEXT,
  overall_b TEXT,
  overall_b_priority TEXT,
  likert_scale TEXT,
  likert_scale_priority TEXT
);
